#! /usr/bin/ruby
=begin
	corrida: retina <archivo.rtn>
	Analizador Lexicografico para el lenguaje retina
Autores
	-Arnaldo Quintero 13-11150
	-Gabriel Gutierrez 13-10625
Ultima modificacion: 25/01/2017
=end

require_relative 'retina_parser.rb'

def main
  #chequear extension del archivo
  unless ARGV[0].end_with? ".rtn"
    abort("Por favor introduzca un archivo valido en formato .rtn")
  end

  #abrir el archivo
  begin
    file = File.read(ARGV[0])
  rescue
    puts "Archivo no Encontrado"
    return
  end

  #crear lexer, parser
  lexer = Lexer.new(file)
  parser = Parser.new

  #leer tokens
  lexer.leerPorLinea

  #parsear input
  ast = parser.parse lexer.tokens

  #imprimir AST
  if !lexer.errors.empty?
    puts lexer.errors
  else
    if !parser.errors.empty?
      puts parser.errors
    else
      begin
        x =  ast.check
        x.print_
      rescue RuntimeError => e
        puts e
      end
    end
  end

  return
end

#llamada a la funcion
main
